/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.awt.event.*;
import java.beans.PropertyVetoException;
/**
 *
 * @author Administrator
 */
public class circlePanel extends javax.swing.JPanel implements ActionListener{
    private int offset = 0;

    /**
     * Creates new form stepPanel
     */
    public circlePanel() {
        initComponents();
        cirUp.addActionListener(this);
        cirDown.addActionListener(this);
        cirFld.addActionListener(this);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cirUp = new javax.swing.JButton();
        cirDown = new javax.swing.JButton();
        offLabel = new javax.swing.JLabel();
        cirFld = new javax.swing.JTextField();

        cirUp.setText("+1");

        cirDown.setText("-1");

        offLabel.setText("Офсет на кръга");

        cirFld.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(offLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cirUp, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cirDown, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(cirFld))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(offLabel)
                        .addGap(18, 18, 18))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cirFld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cirUp)
                    .addComponent(cirDown))
                .addContainerGap())
        );

        cirUp.getAccessibleContext().setAccessibleName("btnUp");
        cirDown.getAccessibleContext().setAccessibleName("btnDown");
    }// </editor-fold>//GEN-END:initComponents

    public int getOff(){
        return this.offset;
    }

    public void setOff(int off) throws PropertyVetoException{
        int oldOff = this.offset;
        this.offset = off;
        fireVetoableChange("offset", oldOff, this.offset);
        firePropertyChange("offset", oldOff, this.offset);
        cirFld.setText(Integer.toString(this.offset));
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cirDown;
    private javax.swing.JTextField cirFld;
    private javax.swing.JButton cirUp;
    private javax.swing.JLabel offLabel;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        try{
        if ((e.getSource()).equals(cirUp)) setOff(getOff()+1);
        if ((e.getSource()).equals(cirDown)) setOff(getOff()-1);
        if ((e.getSource()).equals(cirFld)) setOff(Integer.parseInt(cirFld.getText()));
                } catch (Exception ve){
                    System.out.println("Exception caught!" + ve);
                }
    }
}
